const express = require('express');
const app = express();
const http = require('http');
const server = http.createServer(app);
const { Server } = require("socket.io");
const io = new Server(server);
const path = require('path');
app.use(express.static(path.join(__dirname + '/index.html')));
var cors = require('cors');
app.use(cors());